set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER user1 WITH PASSWORD 'password';
    ALTER USER user1 WITH SUPERUSER CREATEDB CREATEROLE REPLICATION BYPASSRLS PASSWORD 'password';
    CREATE DATABASE covid OWNER user1;
    GRANT ALL PRIVILEGES ON DATABASE covid TO user1;
EOSQL