"""Initial migration

Revision ID: 5755339128ad
Revises: 
Create Date: 2024-06-24 11:20:10.065173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5755339128ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('virus_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('lineage', sa.String(), nullable=False))
        batch_op.drop_column('segment')
        batch_op.drop_column('virus')
        batch_op.drop_column('length')
        batch_op.drop_column('gisaid_epi_isl')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('virus_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gisaid_epi_isl', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('length', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('virus', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('segment', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('lineage')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
