"""Reinitializing migrations.

Revision ID: f2cda0b07d26
Revises: 
Create Date: 2024-07-14 19:51:36.259807

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f2cda0b07d26'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_location', schema=None) as batch_op:
        batch_op.drop_column('state')

    with op.batch_alter_table('virus_data', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('lineage',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('strain',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               nullable=False)
        batch_op.alter_column('division',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('location',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('region_exposure',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('country_exposure',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('division_exposure',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('age',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('sex',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('originating_lab',
               existing_type=sa.BIGINT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('submitting_lab',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('date_submitted',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('virus_data', schema=None) as batch_op:
        batch_op.alter_column('date_submitted',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('submitting_lab',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('originating_lab',
               existing_type=sa.String(),
               type_=sa.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('sex',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('age',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('division_exposure',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('country_exposure',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('region_exposure',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('location',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('division',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('strain',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('lineage',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('lab_location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
